version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: hakaton_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hakaton
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:hakaton@db:5432/hakaton_db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - backend_net
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  pgdata:

networks:
  backend_net: